### ISSUE TITLE
EAP RN08

### ISSUE THREAD

**Issue by rafaatasso** [beatriz-valio-weiss/INE5608-APS#22]
- Especificar melhor o RN08, faltam detalhes de como são equiparadas as horas e dia (ou semana ou seja la o que for) e como ele vai ser feito

**Comment by AndreBezBirolo** [comment]
RN08.O sistema fica responsável por equiparar as horas trabalhadas através de comparação do total de horas trabalhadas semanalmente nos agendamentos dos funcionários.

**Comment by AndreBezBirolo** [comment]
RN08.O sistema fica responsável por equiparar as horas trabalhadas através de comparação do total de horas trabalhadas semanalmente nos agendamentos dos funcionários.
